import Navbar from '@/components/navbar'
import { Roboto_Flex } from 'next/font/google'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from 'next'
import './globals.css'

const roboto_flex  = Roboto_Flex({ 
  weight:['400','700','800'],
  style:['normal'],
  subsets: ['latin'],
  display:'swap' ,
})

export const metadata: Metadata = {
  title: 'Internet magazine',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uz" className={roboto_flex.className}>
      <body>
        <Navbar/>
        <ToastContainer />
        {children}
      </body>
    </html>
  )
}
